elfloader-tool/src/arch-arm/boot.c
elfloader-tool/src/arch-arm/plat-zynq7000/platform_init.c
elfloader-tool/src/arch-arm/plat-zynq7000/sys_fputc.c
elfloader-tool/src/arch-arm/plat-zynq7000/sys_fputc.h

The Zynq7000 UART is not initialized by default. On real hardware U-boot
will perform the correct initialization, but in QEMU there is no
initialization done. This commit enables the UART in elfloader so that
it will work both on the hardware and in QEMU.

Enable UART during initialization on Zynq7000 platform

---

elfloader-tool/Kconfig
elfloader-tool/src/plat/imx6/monitor.S
elfloader-tool/src/plat/imx6/platform_init.c

The elfloder for i.MX6 sabre now can be configured
to load the kernel in secure monitor, secure supervisor,
and nonsecure supervisor.

elfloader: support to load the kernel in NS SVC

---

common-tool/Makefile.flags
common-tool/files_to_obj.sh
elfloader-tool/Makefile
elfloader-tool/gen_boot_image.sh
elfloader-tool/include/arch-arm/elfloader.h
elfloader-tool/include/plat/zynqmp/platform.h
elfloader-tool/include/plat/zynqmp/sys_fputc.h
elfloader-tool/src/plat/zynqmp/platform_init.c
elfloader-tool/src/plat/zynqmp/smp.c
elfloader-tool/src/plat/zynqmp/sys_fputc.c

This pull request adds AARCH32 and AARCH64 support for the Xilinx Zynq UltraScale+ MPSoC. Tested on the ZCU102 development board.

Zcu102 7.0.0

---

common-tool/common.mk

If binutils was configured with --enable-deterministic-archives, the D
option is enabled by default, which it is for Ubuntu. For Fedora it is
not enabled by default, so ar invokations with the same parameters
results in different binaries.
Machine and script:
```
[seL4test]$ cat /proc/cpuinfo | grep "processor"
processor	: 0
processor	: 1
processor	: 2
processor	: 3
[seL4test]$ uname -rom
4.15.3-300.fc27.x86_64 x86_64 GNU/Linux
[seL4test]$ ar --version
GNU ar version 2.29-6.fc27
Copyright (C) 2017 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
[seL4test]$ cat reproducible.sh 
#!/bin/sh
THREADS=$1
CONFIG=$2 …
```

Make library builds deterministic by passing D to ar utility

---

elfloader-tool/src/arch-arm/armv/armv8-a/64/mmu-hyp.S

Configure the EL2_TCR register with the correct PS value.

elfloader: support 40-bit PA

---

elfloader-tool/src/plat/zynqmp/smp.c
elfloader-tool/src/plat/zynqmp/smp_head.S

This commit just adds support for enabling SMP mode on the zynqmp. There's also a commit that disables the yaml loader warning.

Zcu102 smp

---

elfloader-tool/src/arch-riscv/sys_fputc.c
elfloader-tool/src/binaries/efi/efi_fputc.c
elfloader-tool/src/plat/am335x/sys_fputc.c
elfloader-tool/src/plat/apq8064/sys_fputc.c
elfloader-tool/src/plat/bcm2837/sys_fputc.c
elfloader-tool/src/plat/exynos4/sys_fputc.c
elfloader-tool/src/plat/exynos5/sys_fputc.c
elfloader-tool/src/plat/fvp/sys_fputc.c
elfloader-tool/src/plat/hikey/sys_fputc.c
elfloader-tool/src/plat/imx31/sys_fputc.c
elfloader-tool/src/plat/imx6/sys_fputc.c
elfloader-tool/src/plat/imx7/sys_fputc.c
elfloader-tool/src/plat/imx8mq-evk/sys_fputc.c
elfloader-tool/src/plat/odroidc2/sys_fputc.c
elfloader-tool/src/plat/omap3/sys_fputc.c
elfloader-tool/src/plat/qemu-arm-virt/sys_fputc.c
elfloader-tool/src/plat/rockpro64/sys_fputc.c
elfloader-tool/src/plat/tk1/sys_fputc.c
elfloader-tool/src/plat/tx1/sys_fputc.c
elfloader-tool/src/plat/tx2/sys_fputc.c
elfloader-tool/src/plat/zynq7000/sys_fputc.c
elfloader-tool/src/plat/zynqmp/sys_fputc.c

I've been wondering about this for some time, is there a reason why LF CR is used and all elfloader logs contain an empty line between each line (on many systems). Or is this just a mistake and it should always have been CR LF actually?

use CR LF as line break and not LF CR

---

cmake-tool/helpers/environment_flags.cmake

By building a program which provides `main()`, we were assuming that
there is a libc available to compiler. This is not the case for the Red
Hat provided cross-compilers which are intended for use in freestanding
environments (the example given is kernel code). Given that the seL4
build system assumes a freestanding environment it is sensible to only
check that the compiler being used is capable of building such programs.
This change alters the code built when testing compiler options in
`environment_flags.cmake`, and also adds fixed options to force the
compiler to not link against the stdlib or include crt objects. By doing
so we avoid any requirement for a target libc on the build host.

Don't attempt to build hosted programs to test GCC

---

elfloader-tool/src/plat/zynq7000/platform_init.c

Under some QEMU versions (e.g. 5.1), reinitializing the UART clock control register is necessary as a QEMU regression does not set up clock correctly, despite setting the correct reset values in the respective registers. Rewriting the value outside the reset procedure results in correct clock setups.

QEMU/zynq7000 workaround: re-init UART clock 

---

cmake-tool/helpers/environment_flags.cmake

The variable CMAKE_C_COMPILER_VERSION should be set by CMake already,
printing the generic gcc output seem just a artifact from testing. If
the output of this command should be captured to overwrite the variable
CMAKE_C_COMPILER_VERSION, then the keyword OUTPUT_VARIABLE is missing.
But even then, the proper cross compiler must be called using
${CROSS_COMPILER_PREFIX}gcc for this to make sense.

CMake: remove debug output artifact

---

elfloader-tool/CMakeLists.txt

fix regex to use the dot correctly, we expect really a dot here and not "any" chars (which also matched the dot, but it seem semantically wrong)

CMake: fix regex to use the dot correctly

---

elfloader-tool/CMakeLists.txt
elfloader-tool/src/plat/imx6/monitor.S
elfloader-tool/src/plat/tk1/monitor.S

address https://github.com/seL4/seL4_tools/issues/47 and exclude monitor.S is CONFIG_ARM_MONITOR_HOOK is not active

exclude monitor.S is CONFIG_ARM_MONITOR_HOOK is not active

---

elfloader-tool/src/plat/imx6/monitor.S
elfloader-tool/src/plat/tk1/monitor.S

The check in elfloader-tool/src/plat/imx6/monitor.S and elfloader-tool/src/plat/tk1/monitor.S must be done after including gen_config.

fix ElfloaderMonitorHook check

---

cmake-tool/helpers/application_settings.cmake

Tested well and works under U-Boot using bootefi.
Signed-off-by: Samuel Tyler <samuel.tyler005@gmail.com>

Move ElfloaderImage for RockPro64 from binary to UEFI

---

cmake-tool/helpers/application_settings.cmake
elfloader-tool/src/arch-arm/drivers/smp-imx6.c
elfloader-tool/src/drivers/uart/imx-uart.c
elfloader-tool/src/plat/imx6/monitor.S
elfloader-tool/src/plat/imx6/platform_init.c

Patch is part of a series of patches to add support for the i.MX6 Nitrogen6_SoloX board
* https://github.com/seL4/camkes-tool/pull/57
* https://github.com/seL4/seL4/pull/309

camke/elfloader add i.MX6 Nitrogen6_SoloX board

---

elfloader-tool/src/arch-arm/sys_boot.c

EFI configs don't call clear_bss (because their linker scripts don't
have a bss section) and as they use a different linker script that can't
as easily declare a core_stack_alloc symbol, we put it back here.
Signed-off-by: Kent McLeod <kent@kry10.com>

elfloader: Put back core_stack_alloc for EFI

---

elfloader-tool/include/arch-arm/32/mode/arm_generic_timer.h
elfloader-tool/include/arch-arm/64/mode/arm_generic_timer.h
elfloader-tool/src/arch-arm/smp_boot.c
elfloader-tool/src/plat/odroidc2/platform_init.c

Any platform that is not configured with HYP but that uses the arm generic timer uses the virtual counter in the kernel rather than the physical counter. The virtual counter is offset from the physical counter by the virtual offset register, which has no fixed rest value and is only accessible to EL2 and EL3. This value needs to be reset by the bootloader while it is still running in EL2.
This is likely required for all platforms using the ARM generic timer, but currently only presents an issue for ODroid-C2 in our testing matrix.
Blocks https://github.com/seL4/seL4/pull/357

Reset CNTVOFF at boot for ODroid-C2

---

elfloader-tool/src/plat/apq8064/platform_init.c
elfloader-tool/src/plat/bcm2711/platform_init.c
elfloader-tool/src/plat/bcm2837/platform_init.c
elfloader-tool/src/plat/exynos5/platform_init.c
elfloader-tool/src/plat/fvp/platform_init.c
elfloader-tool/src/plat/hikey/platform_init.c
elfloader-tool/src/plat/imx7/platform_init.c
elfloader-tool/src/plat/imx8m-evk/platform_init.c
elfloader-tool/src/plat/qemu-arm-virt/platform_init.c
elfloader-tool/src/plat/rockpro64/platform_init.c
elfloader-tool/src/plat/tk1/platform_init.c
elfloader-tool/src/plat/tx1/platform_init.c
elfloader-tool/src/plat/tx2/platform_init.c
elfloader-tool/src/plat/zynqmp/platform_init.c

When the kernel runs in EL1 on a platform with the arm generic timer the virtual counter is used. MCS can only correctly schedule in the first 3/8ths of representable time so must ensure that the offset is reset for the virtual timer while the bootloader is still in EL2 as EL1 cannot change the offset used to generate the virtual counter value.

Reset CNTVOFF on all arm generic timer platforms

---

elfloader-tool/include/arch-riscv/elfloader.h

The kernel entry uses word_t and expects values in a4 and a5.
Without this, all harts think they are primary and the kernel setup code gets very confused.

riscv: Fix 32-bit hart and core ID passing

---

elfloader-tool/include/arch-riscv/sbi.h
elfloader-tool/src/arch-riscv/boot.c
elfloader-tool/src/arch-riscv/crt0.S

seL4 and librarys assume booting on hart1 while
Opensbi and U-boot pick a hart at random.
This patch uses an SBI call to start the elfloader on hart1
if a different hart has been choses.
Credits go to Peter Chubb for the straw-man example.
Signed-off-by: Oliver Scott <Oliver.Scott@data61.csiro.au>

risc-v: switch to hart1

---

elfloader-tool/CMakeLists.txt

The 'echo' calls was not generating the header files properly, adding in
whitespace between the '>' symbols allows CMake to properly parse the
arguments and invoke the calls correctly.

CMakeLists: Fix image start addr generation call

---

elfloader-tool/CMakeLists.txt

There's a weird interaction with a similar command in the capdl-loader
in the capDL repository which causes CMake to ignore the
platform_sift.py call in this repository. Merging the two
`add_custom_command` calls tells CMake to not ignore it.

CMake: Work around a weird CMake bug

---

elfloader-tool/CMakeLists.txt

The CMakeLists.txt file was missing the PLATFORM_SIFT variable.

CMake: Add missing PLATFORM_SIFT variable

---

elfloader-tool/src/arch-riscv/crt0.S

Binary images do not have the luxury of having a proper loader load
the elfloader into memory correctly and zero out the BSS, so we have to
do it ourselves.

riscv: Add clear_bss to crt0 if image is binary

---

elfloader-tool/src/arch-riscv/crt0.S

03627581 replaced t3 with s0 for holding the ID of the current HART,
there is a later load immediate instruction which clobbers s0, so we fix
the branch comparison to use s1 instead of s0.

riscv: Use s1 instead of s0 for branch on _start1

---

cmake-tool/helpers/rootserver.cmake

Setting `PLATFORM` to a well defined value when running the clean step avoids running into conflicts where it happens to be defined as environment variable already with a value OpenSBI does not support.
See also https://github.com/riscv/opensbi/issues/217 that I have filed as potential issue there.

CMake: pass PLATFORM for OpenSBI clean step

---

cmake-tool/helpers/application_settings.cmake
elfloader-tool/src/plat/odroidc4/platform_init.c

Adds the ODroid C4 as a valid device.

Add ODroid C4 support

---

elfloader-tool/CMakeLists.txt

When generating header files, the "\\n" sequence doesn't generate a
newline character unless -e is given to echo.
Signed-off-by: Kent McLeod <kent@kry10.com>

elfloader: Use file(GENERATE) for static headers

---

cmake-tool/helpers/cpio.cmake

macOS does not have a group named `root`, so we use numeric user IDs to
get reproducible CPIO archives.
Signed-off-by: Matthew Brecknell <matt@kry10.com>

cmake-tool: use numeric user IDs in cpio

---

elfloader-tool/src/arch-riscv/crt0.S

This change switches to any start hart specified by CONFIG_FIRST_HART_ID instead of fixed id 1.
Signed-off-by: Yanyan Shen <yshen@hybridkernel.com>

elf-loader: Switch to any start hart instead of 1

---

elfloader-tool/include/arch-arm/elfloader.h
elfloader-tool/include/arch-riscv/elfloader.h
elfloader-tool/include/elfloader_common.h
elfloader-tool/include/types.h
elfloader-tool/src/arch-arm/sys_boot.c
elfloader-tool/src/arch-riscv/boot.c
elfloader-tool/src/common.c

Use word_t and sword_t to be architecture agnostic. 
This also requires a change in the kernel, see https://github.com/seL4/seL4/pull/494

use proper types for parameters

---

elfloader-tool/src/arch-riscv/crt0.S

Pass a1 as received from OpenSBI to main's second argument

---

elfloader-tool/src/arch-arm/cpuid.c

The existing print_cpuid function displays the incorrect value
for Cortex-A35. (See issue #43).
This change makes CPUID determination an explicit switch statement
rather than attempting to automatically determine it through
masking certain bits.
Note: At some level this will be a regression as it now only
prints the textual id for Cortex-A35 and no other CPU.
Improvements to list other CPUID mappings is welcome, unfortunately
the only platform I have access to for testing is Cortex-A35.

Fix ARM CPUID printing

---

elfloader-tool/src/arch-arm/cpuid.c

Ensure that part determination is per-implementer.
See also #109
Signed-off-by: Ben Leslie <benno@brkawy.com>

Refactor CPUID printing

---

elfloader-tool/include/binaries/efi/efi.h
elfloader-tool/include/types.h
elfloader-tool/src/string.c

- remove trivial define `BYTE_PER_WORD`
- add define `WORD_MAX`
- use bit numbers for EFI constants

elfloader: cleanup defines

---

cmake-tool/helpers/rootserver.cmake

- improve comments and variable names
- allow platforms to customize OpenSBI parameters
- `OPENSBI_PLAT_XLEN`
- `OPENSBI_PLAT_ISA`
- `OPENSBI_PLAT_ABI`

elfloader/risc-v: improve OpenSBI support

---

elfloader-tool/src/arch-riscv/crt0.S

simplify assembly code by inlining SBI call.

elfloader/risc-v: inline spi_probe_extension

---

elfloader-tool/CMakeLists.txt

The parameter is optional and defaults to 'arm', which is a semantic error when building RISC-V targets. This does not cause any issues so far, because the value is mostly unused.
This change requires https://github.com/seL4/seL4/pull/642
Test with seL4/seL4#642

elfloader: pass KernelSel4Arch to python scripts

---

cmake-tool/helpers/application_settings.cmake

If executables are loaded as ELF instead of Binary, U-Boot can detect
whether to invoke them in 32 or 64 bit mode.
Signed-off-by: Peter Chubb <peter.chubb@unsw.edu.au>

Change zynqmp to use ELF executables

---

elfloader-tool/CMakeLists.txt

When running a python script from CMake, explicitly invoke Python via
the `PYTHON3` variable defined in the seL4 CMake config, rather than
relying on the script to specify its interpreter with `#!`.
This makes it easier to override the Python interpreter used for all
Python scripts called from CMake builds.

cmake: invoke python3 explicitly

---

elfloader-tool/src/arch-riscv/crt0.S

- Set a valid stack before calling any C function so that memory and
registers don't get corrupted.
- Keep track of the DTB address so that it's still in a1 when main is
called even if we needed to switch to a different HART.
- If the HSM extention isn't present, then try and call main on the
current HART.
- Suspend HARTs that exceed CONFIG_MAX_NUM_NODES.
Signed-off-by: Kent McLeod <kent@kry10.com>

elfloader,RISC-V: Fix early boot issues

---

elfloader-tool/src/arch-arm/sys_boot.c

When use bootloader DTB, it always print 0 as the DTB addrss, the print
usage wrong variable.
Signed-off-by: Lihua Zhao <lihuazhao.cn@gmail.com>

correct the print dtb address

---

elfloader-tool/include/arch-riscv/sbi.h

elfloader/risc-v: add missing brackets (it's a macro, so brackets are required to ensure it's an atom)
elfloader/risc-v: fix register naming

elfloader/risc-v: minor SBI wrapper code cleanup

---

elfloader-tool/include/arch-arm/64/mode/assembler.h
elfloader-tool/src/arch-arm/armv/armv8-a/64/mmu-hyp.S
elfloader-tool/src/arch-arm/armv/armv8-a/64/mmu.S

Memory region type: "Normal memory, write-through" was added.
Signed-off-by: Nataliya Korovkina <malus.brandywine@gmail.com>
Test with: seL4/seL4#834

elfloader/arm64: add "write-through" support

---

cmake-tool/helpers/application_settings.cmake
elfloader-tool/src/plat/maaxboard/platform_init.c

This pull request is a call for feedback and comment on an initial implementation for supporting seL4 on the Avnet MaaXBoard, with the intention of the changes below being merged back to the main seL4_tools repository. This pull request is dependent on another pull request which provides the core support for the MaaXBoard in the seL4 repository; this can be found [here](https://github.com/seL4/seL4/pull/829).
This pull request contains the following changes:
* The creation of a platform_init file for the MaaXBoard, performing the necessary resets for initialising the board.
* Renaming of the specific `KernelPlatformImx8mq-evk` platform from `cmake-tool/helpers/application_settings.cmake`, creating a common `KernelPlatformImx8mq` platform, which can be used by both the imx8mq-evk …

Add support for the Avnet MaaXBoard (seL4_tools)

---

cmake-tool/helpers/cpio.cmake

I can't see where `append` is used and the git history also does not reveal it.

CMake: remove unused variable

---

cmake-tool/helpers/rootserver.cmake
elfloader-tool/CMakeLists.txt

When using a customized build system, `ElfloaderImage` could not be set due to some usage error. Printing a user friendly warning message instead of running into the rather strange CMake error message
```
CMake Error at /host/OS-SDK/pkg/sdk-sel4-camkes/tools/seL4/cmake-tool/helpers/rootserver.cmake:161 (if):
if given arguments:
"IN_LIST" "binary_efi_list"
Unknown arguments specified
```

CMake: warn if ElfloaderImage is missing

---

cmake-tool/helpers/shoehorn.py

Improve error handling. Due to some other error I ran into a situation where `kernel.elf` was missing in the CPIO archive and `shoehorn` gave a rather odd error message that `kernel_elf` is used without being defined. Now the tool clearly says that `kernel.elf` is missing in the CPIO archive.

shoehorn: handle missing kernel.elf

---

cmake-tool/helpers/application_settings.cmake

Without adding the zynqmp subplatforms (zcu102, ultra96, ultra96v2), sel4test can only be compiled for the generic zynqmp platform. While this is compatible with the ZCU102, the Ultra96 platforms use a different serial port, so the sel4test logs would be unreadable.
This commit allows sel4test to be compiled with -DPLATFORM=ultra96 and -DPLATFORM=ultra96v2.
Signed-off-by: Chris Guikema <chrisguikema@dornerworks.com>

cmake_tool: add zynqmp to platform_strings

---

misc/.gitlint

Setting `regex-style-search=true` avoids a warning. 
```
WARNING: I1 - ignore-by-title: gitlint will be switching from using Python regex 'match' (match beginning) to
'search' (match anywhere) semantics. Please review your ignore-by-title.regex option accordingly.
To remove this warning, set general.regex-style-search=True. 
More details: https://jorisroovers.github.io/gitlint/configuration/#regex-style-search
```
So far, gitlint uses Python's `re.match()` (match from start) by default, but it will change to use the more generic `re.search()` (match anywhere) in the future. Since we prefer `re.search()`, the new behavior is enabled  explicitly.  For more details see also
https://jorisroovers.com/gitlint/configuration/#regex-style-search.

gitlint: enable regex-style-search explicitly

---

elfloader-tool/src/common.c

There is no reason to shadow the variable, might come from some refactoring

elfloader: don't shadow variable

---

cmake-tool/helpers/rootserver.cmake

Closes https://github.com/seL4/seL4_tools/issues/164. Perhaps we should use `config_option` to be consistent with other CMake options? Happy to change the patch to use that instead, I don't know enough about CMake to know which is better.

Fix `UseRiscVOpenSBI` CMake option

---

cmake-tool/helpers/application_settings.cmake

This is in order to be consistent with the BCM2837 (Raspberry Pi 3) and because executing AArch32 for the RPi4B requires binary.

Set RPi4B builds to produce binary images

---

cmake-tool/helpers/rootserver.cmake

Default args for gcc have changed; we need to fix the args given to the compiler.

Fix RISC-V compilation with recent GCC

---

elfloader-tool/CMakeLists.txt

This option generates an intermediate build file, elfloader.o, that can be combined in a separate build step with an archive.o containing the cpio archive with the kernel and rootserver images to load. This enables the elfloader to be installed by copying the elfloader.o and generated linker file to an install location and a future build step can link with a supplied archive.o into a bootable elfloader image using something like:
aarch64-unknown-linux-gnu-gcc -march=armv8-a elfloader.o archive.o \
-o elfloader -Wl,-T linker.lds_pp -nostdlib -static -lgcc

elfloader: Add ElfloaderPrecompile option

---

cmake-tool/helpers/cpio.cmake

This changes `touch` from using the `-d@0` argument, which is not supported on BSD, to a generic date format that is.

Change touch to be portable

---

.github/workflows/sel4test-hw.yml

Update to current node16 versions. The old node12 actions are deprecated and will stop working.

github: bump GitHub action versions

---

.github/workflows/sel4test-hw.yml

This was deleted by accident in commit 75fc8008 from PR https://github.com/seL4/seL4_tools/pull/183

CI: bring back compiler to matrix

---

cmake-tool/helpers/environment_flags.cmake

crt[begin|end].o files are used for C++ projects. While they usually exist in GCC, they may or may not exist in LLVM builds that don't rely on GCC toolchain, and typically require a separate (optional) compiler-rt/cxx library to build.
This commit allows building projects without crt[begin|end].o files if they do not exist.

lld: Enable building C projects without cxx crt files

---

misc/astylerc

Release 3.0 of astyle replaced this option with
'max-continuation-indent'. The replaced option is already in the astylerc so we just need to remove the option here.
Further information can be found in the release notes: https://astyle.sourceforge.net/news.html

misc: remove deprecated astyle option

---

cmake-tool/helpers/application_settings.cmake

The imx8mp-evk as like with the other imx8m-* platforms require the resulting image to just be a binary and not an ELF or other special formats.

cmake: Support binary build for imx8mp-evk

---

misc/style-c.sh

We use the seL4 style check for sDDF and most people who try to run the style check offline end up running into weird issues since they don't have it installed.

misc: check that astyle exists

---

cmake-tool/helpers/application_settings.cmake

The port of the hardware debug API to aarch64 has increased the size of some debug images to the point that the address range the image is loaded at overlaps with the address range the elf-loader relocates to and expects to run at. This was solved on aarch64 by shifting the uboot load address to 0x42000000. We do not differentiate between aarch32 and aarch64 images in uboot, and the aarch32 elfloader is not relocated, so the configuration in this commit must be changed to have the aarch32 elfloader expect to be executed from the new load address.

Shift 32-bit image start address on imx8mm

---

cmake-tool/helpers/check_arch_compiler.cmake

Avoid odd error messages about an invalid number of parameters in case `TRIPLE` is empty. This happens with a customized build system.

cmake: use quotes

---

elfloader-tool/src/plat/tx2/platform_init.c

Only results in a compilation error on newer GCC versions.
What confuses me though is this only happens for me in sel4bench, but not sel4test. I believe I'm using the same compiler in both projects, but se4lbench results in a unitialised warning that is treated as a compile error. sel4test does not even print the warning?

elfloader: initialise stack allocated struct

---

cmake-tool/README.md

GettingStarted page was renamed and was not describing what this page claimed. Point to a sub-heading that at least sort-of does.

cmake-tool: update GettingStarted link

---

cmake-tool/helpers/application_settings.cmake

Prevents building OpenSBI automatically in Cmake builds.

Support for Cheshire (CVA6)

---

elfloader-tool/src/arch-arm/sys_boot.c

The _end symbol is declared as char[]. Newer compilers raise warnings about array out of bounds access here:
error: array subscript -1 is outside array bounds of ‘char[]’ [-Werror=array-bounds]

elfloader: cast linker symbol to avoid warining

---

elfloader-tool/src/arch-arm/sys_boot.c

Part of #93 enabled checking arg0 for a dtb pointer when loading as a binary. However because several CONFIG_IMAGE_BINARY configurations don't sanitize arg0 before calling main it's not yet safe to dereference the variable as a valid pointer.

elfloader: Revert part of #93

---

cmake-tool/helpers/environment_flags.cmake

When the kernel is configured to support TPIDRURO as the thread id register on aarch32, our default user level compilers can use optimised TLS accesses.

cmake,aarch32: Allow hardware TLS on some configs

---

cmake-tool/README.md
cmake-tool/all.cmake
cmake-tool/base.cmake
cmake-tool/common.cmake
cmake-tool/default-CMakeLists.txt
cmake-tool/helpers/application_settings.cmake
cmake-tool/helpers/cakeml.cmake
cmake-tool/helpers/configure_file.cmake
cmake-tool/helpers/cross_compiling.cmake
cmake-tool/helpers/dts.cmake
cmake-tool/helpers/environment_flags.cmake
cmake-tool/helpers/external-project-helpers.cmake
cmake-tool/helpers/make.cmake
cmake-tool/helpers/nanopb.cmake
cmake-tool/helpers/rust.cmake
cmake-tool/polly_toolchains/FindPolly.cmake
cmake-tool/projects.cmake
elfloader-tool/CMakeLists.txt
elfloader-tool/helpers.cmake

Compatibility with versions <3.10 is going away.
As it happens, we're not using any CMake features that have changed between 3.7 and 3.16, so bump the lowest version to 3.16.

Bump CMake version

---

cmake-tool/helpers/application_settings.cmake
cmake-tool/helpers/elf_sift.py
cmake-tool/helpers/shoehorn.py
elfloader-tool/CMakeLists.txt

Correct the calculated memory needed to load an elf image. Using only
the p_memsz value ignores gaps between segments; instead calculate the
first+last addresses using p_vaddr & p_memsz.
As get_memory_usage in elf_sift.py now can calculate correct memory
usage from a list of ELF segments, a more accurate upper bound on
memory usage for the loaded apps is possible and the old fudge
factor is no longer needed.
Thanks to @sleffler for the patch.

Reduce fudge factor from shoehorn and strip elf files before loading

---

elfloader-tool/src/arch-arm/drivers/smp-spin-table.c

Very simple driver for booting multiple cores using the device tree tooling infrastructure.

elfloader,rpi4: Add smp-spin-table driver

---

elfloader-tool/src/arch-riscv/boot.c

Same as #214 but for RISC-V.
This creates an error for some build configs.

elfloader: cast linker symbol to avoid warning

---

misc/style-cmake.sh

As decided in the most recent TSC meeting, bump the required cmake version to the latest available at the moment. Update command line options accordingly (`--max-subargs-per-line` option no longer exists).
This will change/complain about the style in many of our existing `cmake` files, but at some point we do need to switch, because to keep the old version working, we'd need to pin too many other packages to old versions and thereby downgrade other tools.
See also https://github.com/seL4/seL4/pull/1479

Bump required cmake version

---

elfloader-tool/include/drivers/common.h

Because of GCC bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99587 using has_attribute is not reliable and can give compile warnings that will be turned into errors because of -Werror.
The retain atribute was added to support linking with LLVM's linker in commit be8277a84c0c59b472909877540d55d53739001e.
Cross reference: https://github.com/seL4/seL4_libs/pull/103.

elfloader: limit retain to clang

---

cmake-tool/helpers/application_settings.cmake

Cheshire loads images over JTAG (OpenOCD + GDB) and so ELF files make it easier to just load seL4 and then go. Binary files *work* but need to be manually loaded at the correct address, so are more annoying to work with. In the case of U-Boot anyhow, we need to use uImage and it is (a) hard to load using GDB (need to offset 64 bytes for the header every time you load it), and b) can be generated by the `make-uimage` from seL4_tools easily (and this is what is done by our machine queue setup locally).
Also, the set address of 0x80200000 breaks the elfloader currently as the location of the embedded DTB overlaps the kernel load address and so the current binary images *cannot* be used to boot seL4.
With: https://github.com/seL4/docs/pull/297

elfloader: use ELFs on Cheshire; change start addr
