cmake-tool/rust_targets/aarch64-sel4-none.json

Built  and run hellorust for imx8mq-evk using this json file, not sure if all of the args to gcc are correct?

Added aarch64 target json file for rust build 

---

cmake-tool/rust_targets/aarch32-sel4-none.json

Tested against sabre in simulator.

The aarch32 json target

---

cmake-tool/helpers/environment_flags.cmake

The FPU checks need to check that the compiler can compile programs with
the desired FPU options AND link against compiler runtime libraries with
the correct FPU ABI. If either of these conditions aren't met, then we
can't build programs correctly.
We use the standard check_c_source_runs CMake function which inherits
the compilation options that have been set already. Unfortunately it
doesn't inherit any changes to CMAKE_<LANG>_LINK_EXECUTABLE variables
which is what we use to set the compiler libraries and so we need to
specify those again manually. This both compiles and links our test
program.  In cross-compiling environments, the run stage will be
skipped; yet this is still sufficient to pick up ABI mismatches.

add_fpu_compilation_options: More accurate checks

---

cmake-tool/helpers/rootserver.cmake

Signed-off-by: Axel Heider <axelheider@gmx.de>

Make building BBL image dependent on UseRiscVBBL

---

.github/workflows/pr.yml
.github/workflows/push.yml
LICENSE.md
README.md

This is the basic set from https://github.com/seL4/ci-actions

Add basic style CI checks

---

cmake-tool/helpers/rootserver.cmake
elfloader-tool/include/arch-riscv/elfloader.h
elfloader-tool/include/binaries/elf/elf.h
elfloader-tool/include/binaries/elf/elf32.h
elfloader-tool/include/binaries/elf/elf64.h
elfloader-tool/include/elfloader_common.h
elfloader-tool/include/fdt.h
elfloader-tool/include/types.h
elfloader-tool/src/binaries/elf/elf.c
elfloader-tool/src/binaries/elf/elf32.c
elfloader-tool/src/binaries/elf/elf64.c
elfloader-tool/src/common.c
elfloader-tool/src/fdt.c
elfloader-tool/src/hash.h
elfloader-tool/src/printf.c
elfloader-tool/src/string.c
elfloader-tool/src/utils/hash.c

* better 32/64-bit support
* general code quality improvements
* needed for https://github.com/seL4/util_libs/pull/73
* this PR is split out from https://github.com/seL4/seL4_tools/pull/58 to allow merging some things

ElfLoader improvements, better 32/64-bit support

---

elfloader-tool/include/binaries/elf/elf32.h
elfloader-tool/include/binaries/elf/elf64.h
elfloader-tool/include/elfloader_common.h
elfloader-tool/src/arch-arm/sys_boot.c
elfloader-tool/src/arch-riscv/boot.c
elfloader-tool/src/binaries/elf/elf.c
elfloader-tool/src/binaries/elf/elf32.c
elfloader-tool/src/binaries/elf/elf64.c
elfloader-tool/src/common.c
elfloader-tool/src/printf.c

RISC-V SBI/ElfLoader improvements.
Note that this patch builds on top of https://github.com/seL4/seL4_tools/pull/54, so it contains all commits from there.

RISC-V SBI/ElfLoader improvements

---

elfloader-tool/include/binaries/elf/elf32.h
elfloader-tool/include/binaries/elf/elf64.h
elfloader-tool/include/elfloader_common.h
elfloader-tool/include/fdt.h
elfloader-tool/src/arch-arm/sys_boot.c
elfloader-tool/src/arch-riscv/boot.c
elfloader-tool/src/binaries/elf/elf32.c
elfloader-tool/src/binaries/elf/elf64.c
elfloader-tool/src/common.c
elfloader-tool/src/fdt.c
elfloader-tool/src/hash.h
elfloader-tool/src/utils/hash.c

more ELF-Loader code cleanup and improvements.

ELF-Loader code cleanup and improvements

---

elfloader-tool/src/common.c

Signed-off-by: Oliver Scott <Oliver.Scott@data61.csiro.au>
Fixes broken camkes sabre simulation build

trivial: update elf variable name

---

elfloader-tool/CMakeLists.txt
elfloader-tool/src/arch-arm/linker.lds
elfloader-tool/src/arch-arm/sys_boot.c

Fixes issues identified in https://github.com/seL4/seL4_tools/issues/65

Fix issues with zeroing initial bss memory in elfloader

---

elfloader-tool/README.md
elfloader-tool/include/abort.h
elfloader-tool/include/arch-riscv/elfloader.h
elfloader-tool/include/elfloader_common.h
elfloader-tool/src/arch-arm/smp_boot.c
elfloader-tool/src/arch-arm/sys_boot.c
elfloader-tool/src/arch-riscv/boot.c
elfloader-tool/src/common.c
elfloader-tool/src/defaults.c
elfloader-tool/src/drivers/smp/common.c
elfloader-tool/src/drivers/uart/common.c

Code cleanup and small improvements.

EFL-Loader code cleanup and small improvements

---

elfloader-tool/src/arch-arm/smp_boot.c

trivial: Add missing const identifier

---

cmake-tool/helpers/application_settings.cmake
elfloader-tool/src/drivers/uart/imx-lpuart.c
elfloader-tool/src/plat/tqma8xqp1gb/platform_init.c

Add tool support for the tqma8xqp1gb platform.

tqma8xqp1gb support

---

elfloader-tool/include/types.h

Add a build breaker if the compiler settings are wrong.

elfloader: check that _int64_type is 64 bit

---

elfloader-tool/src/arch-riscv/crt0.S

Commit extracted from https://github.com/seL4/seL4_tools/pull/115

elfloader/risc-v: improve comments

---

.github/workflows/sel4test-hw.yml

This is a copy of the same pull request action from seL4/seL4.

github: enable hw-test and hw-build on PRs

---

cmake-tool/simulate_scripts/simulate.py

Pretty much the change from https://github.com/seL4/seL4_tools/pull/143, I find it quite useful from time to time so it would be nice for it to be upstreamed.

Add dry run option to simulate script

---

cmake-tool/helpers/application_settings.cmake

Original PR by @Furao (https://github.com/seL4/seL4_tools/pull/177).

Fix to allow RocketChip to build

---

.github/workflows/sel4test-hw.yml
.github/workflows/sel4test-sim.yml

Similar to https://github.com/seL4/seL4/pull/1154, pick up things from https://github.com/seL4/ci-actions/pull/297

CI: simulation and HW build with LLVM on RISCV

---

cmake-tool/simulate_scripts/simulate.py

This one is small enough to not interfere with other work in progress and it will stop annoying CI complaints.

trivial: style fix for autopep8 version bump

---

cmake-tool/helpers/environment_flags.cmake

Needed for https://github.com/seL4/sel4test/pull/134.

Clang: Add -mno-outline-atomics

---

cmake-tool/README.md

Resource page on docsite is being deleted. Redirecting links to setup page

change link to Resources to setup page
